### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by dgershman** [pjaudiomv/homebrew-awsd#15]
I'm not sure how to get started!  It seems cool, but I'm not sure what this even does.

**Comment by pjaudiomv** [comment]
This repository maintains a [homebrew tap](https://docs.brew.sh/Taps) for [awsd](https://github.com/radiusmethod/awsd). For instructions on installing [awsd](https://github.com/radiusmethod/awsd) please see repository [here](https://github.com/radiusmethod/awsd?tab=readme-ov-file#installation). I have updated the readme to reflect that.

**Comment by dgershman** [comment]
Thank you! I am able to use this now!
